### ISSUE TITLE
issue with terraform-provider-aws

### ISSUE THREAD

**Issue by Arnold1** [johandry/terranova-examples#2]
hi,

I run into the following errors. any idea how to fix it?
```
$ go run main.go
# github.com/terraform-providers/terraform-provider-aws/aws
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/resource_aws_glue_crawler.go:369:47: cannot convert *crawlerInput (type gl
ue.CreateCrawlerInput) to type glue.UpdateCrawlerInput
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:4874:7: spec.ServiceNames undefined (type *appmesh.VirtualRou
terSpec has no field or method ServiceNames)
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:4886:41: spec.ServiceNames undefined (type *appmesh.VirtualRo
uterSpec has no field or method ServiceNames)
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:4902:17: cannot use expandStringSet(vBackends) (type []*strin
g) as type []*appmesh.Backend in assignment
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:4969:7: unknown field 'ServiceName' in struct literal of type
 appmesh.DnsServiceDiscovery
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:4987:44: cannot use spec.Backends (type []*appmesh.Backend) a
s type []*string in argument to flattenStringSet
/Users/arnold1/go/pkg/mod/github.com/terraform-providers/terraform-provider-aws@v1.60.0/aws/structure.go:5028:64: spec.ServiceDiscovery.Dns.ServiceName undefined (typ
e *appmesh.DnsServiceDiscovery has no field or method ServiceName)
```

I changed to: 
```github.com/hashicorp/terraform v0.12.26 // indirect```

I try to run a terraform plan ... to understand if there is a diff... how can tell terraform plan in the code to return if there is a diff? I don't want to run terraform apply btw.

also, how to pass the aws key in the code instead setting it as a env variable?

**Comment by johandry** [comment]
Hi @Arnold1, this is the same solution for the issue in johandry/terranova. 

In your `go.mod` file, try replacing the line `github.com/terraform-providers/terraform-provider-aws v1.60.0` to:
```
github.com/terraform-providers/terraform-provider-aws v1.60.1-0.20191003145700-f8707a46c6ec
```

Then run `go mod tidy` to validate the modules version.

**Comment by johandry** [comment]
Regarding the AWS key (or any AWS credentials), you can pass them as environment variables, configuring the AWS credentials with AWS CLI or in the code.

* As environment variables: Export the env vars `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, as explained [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html). The Terraform provider will take the credentials from the env vars.
* Configuring AWS CLI: if you have the AWS CLI installed, execute: `aws configure`, enter the credentials and they will be set in the file `~/.aws/credentials` as explained [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html). The Terraform provider will take them from the file `~/.aws/credentials`.
* In the code: Modify the provider block in terraform code, like so:
```
provider "aws" {
  region     = "us-west-2"
  access_key = var.access_key
  secret_key = var.secret_key
}
variable "access_key" {}
variable "secret_key" {}
```
Then something like this in the Go code:
```
platform, err := terranova.NewPlatform(code).
...
		Var("access_key", "<your access key>").
		Var("secret_key", "<your secret key>").
```

The access/secret keys can be passed with flags to your program, you can get them from - different - environment variables, from the program config file , hardcoded (not recommended), or any other way.

Let me know if this helps

**Comment by johandry** [comment]
I'm closing this issue as the solution was provided and I've not receive any feedback. 
If the problem persist, please, reopen the issue or a new one. 👍
